-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 23:00:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema buarmabpi5dp0ox4idcp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buarmabpi5dp0ox4idcp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buarmabpi5dp0ox4idcp` DEFAULT CHARACTER SET utf8 ;
USE `buarmabpi5dp0ox4idcp` ;

-- -----------------------------------------------------
-- Table `buarmabpi5dp0ox4idcp`.`Estados_deuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buarmabpi5dp0ox4idcp`.`Estados_deuda` (
  `idEstados_deuda` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstados_deuda`),
  UNIQUE INDEX `nombre_estado_UNIQUE` (`nombre_estado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buarmabpi5dp0ox4idcp`.`deudores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buarmabpi5dp0ox4idcp`.`deudores` (
  `idDeudores` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `valor` DOUBLE NULL,
  `apodo` VARCHAR(45) NULL,
  `Estados_deuda_idEstados_deuda` INT NOT NULL,
  PRIMARY KEY (`idDeudores`),
  INDEX `fk_deudores_Estados_deuda_idx` (`Estados_deuda_idEstados_deuda` ASC) VISIBLE,
  CONSTRAINT `fk_deudores_Estados_deuda`
    FOREIGN KEY (`Estados_deuda_idEstados_deuda`)
    REFERENCES `buarmabpi5dp0ox4idcp`.`Estados_deuda` (`idEstados_deuda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
